server:
  port: 8080

spring:
  config:
    import: optional:classpath:application-secret.yml
  datasource:
    url: jdbc:mysql://localhost:3306/bus?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root          # 你的数据库账号
    password: your_password # 你的数据库密码
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update # 自动更新表结构（已有数据建议用 validate 或 none）

# application.yml
knife4j:
  enable: true